hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    user:
        path: /user/**
        serviceId: user
#        stripPrefix: false
#        sensitiveHeaders:
    auth:
        path: /uaa/**
        url: http://auth:5000
        stripPrefix: false
        sensitiveHeaders:

eureka:
  instance:
    hostname: gateway
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/


server:
  port: 10000
